# [Ctrl]+[Alt]+[R] で各セクションを実行

@service_id = x4kxd6riwt
@api_key = 8Z9GykL8Bd9yvbgcPSF6ztLx1xOv46p9WQzS
@post_id = 2e7co-63j8p

### 全投稿の取得
GET https://{{service_id}}.microcms.io/api/v1/posts
X-MICROCMS-API-KEY : {{api_key}}

### 単投稿の取得
GET https://{{service_id}}.microcms.io/api/v1/posts/{{post_id}}
X-MICROCMS-API-KEY : {{api_key}}